remote_theme : willianjusten/will-jekyll-template

# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "https://soohyun.github.io/geteasy" # the subpath of your site, e.g. /blog
url: "https://soohyun.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Geteasy
user_description: Soohyunoh
user_title: Geteasy
email: letmeshinebrightly@gmail.com
twitter_username: 
github_username:  Soohyunoh
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
